Repository Shivansh2030/thegreatramayan, pull requests merged in 2022-10, with the labels that each got.

#1 Create historyian
  historyian
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#2 Create actors
  actors
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Update historyian
  historyian
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 Update history
  history
Labels: documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 Update historyian
  historyian
Labels: documentation, enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
